services:
  postgres:
    image: postgres:17
    container_name: "postgres-database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "gitpod"
    volumes:
      - pgData:/var/lib/postgresql/data
    networks:
      - application

  app:
    container_name: quarkus-app
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - "QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-database:5432/gitpod"
    depends_on:
      - postgres
    networks:
      - application

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/gitpod -user=postgres -password=123456 -outOfOrder=true -locations=filesystem:/flyway/sql migrate
    depends_on:
      - postgres
    networks:
      - application
    volumes:
      - type: bind
        source: ./src/main/resources/db/migration
        target: /flyway/sql
        read_only: true

volumes:
  pgData:

networks:
  application: